### ISSUE TITLE
N option on netcat doesn't exist on Fedora 30

### ISSUE THREAD

**Issue by qortex** [fohte/rubocop-daemon#11]
I had to remove the `-N` parameter for the `nc` call in `/usr/local/bin/rubocop-daemon-wrapper` because it fails with an error on my Fedora box:

```
nc -N
nc: invalid option -- 'N'
```

Seems to work well without the `N` option for now.

**Comment by fohte** [comment]
Thanks for reporting this, @MicMicMon!

This `nc` command seems to be a GNU version or Ncat, indeed, they don't support `-N` option.

I considered how to detect several versions of `nc` correctly, but I don't know what to do with a Bash script. This is a difficult problem, so I'll try to rewrite the `rubocop-daemon-wrapper` script from Bash to Go.

In the meantime, I'll fix `rubocop-daemon-wrapper` to remove the `-N` option on netcat on Fedora as a workaround.

**Comment by fohte** [comment]
I've fixed the issue with a workaround by e69b6c5!

I'll close this issue, but if you still have any problems, please reopen it. Thanks again for reporting!
