### ISSUE TITLE
Wrapper script invocations can race

### ISSUE THREAD

**Issue by jvilk-stripe** [fohte/rubocop-daemon#12]
## Problem

If you invoke the wrapper script multiple times simultaneously, each invocation can race with one another as they try to delete and read the same status file.

This is very common in the editor setting, where Rubocop can be invoked simultaneously as the user edits different documents.

## Solution

One solution is to use a lock file to prevent simultaneous access. The simplest cross-platform way to do this is via `mkdir`:

```bash
LOCK_PATH="$PROJECT_CACHE_DIR/running.lock"

# Acquire a file lock before proceeding.
# Macs don't support the `lockfile` command, so just use mkdir.
function unlock {
  rm -r $LOCK_PATH 2>/dev/null
}
trap unlock EXIT

i=0
while ! mkdir $LOCK_PATH 2>/dev/null; do
  echo "rubocop-daemon is processing a request; pausing before trying again..." >&2
  sleep 1
  i=$(( $i + 1 ))
  if [ $i -ge 5 ]; then
    echo "Waited more than 5 seconds; ignoring the lock and proceeding." >&2
    break
  fi
done
```

Caveat: I don't know where `trap` may be unavailable. It's possible this won't work in non-bash shells.

**Comment by fohte** [comment]
Thanks for reporting this and suggesting the solution, @jvilk-stripe!

I've fixed the issue in 37066f74ec1d53695edd70a31f75484aa7f95555, so I'll close it.

If you still have any problems, please reopen it. Thanks again for reporting and suggesting the solution!
