### ISSUE TITLE
Wrapper script drops trailing newlines with --stdin option

### ISSUE THREAD

**Issue by jvilk-stripe** [fohte/rubocop-daemon#13]
## Problem

With the --stdin option, the wrapper script uses the following to read the contents of stdin:

```bash
STDIN_CONTENT="$(cat)"
```

However, this drops trailing newlines:
https://stackoverflow.com/questions/40717518/why-does-cat-drop-a-newline

This fails a cop in my current project, which expects a newline at the end of the file.

## Solution

Use workaround 1 from https://stackoverflow.com/a/15184414:

```bash
# Read file without trimming trailing newline. See Workaround 1 at https://stackoverflow.com/a/15184414
STDIN_CONTENT="$(cat; printf x)"
STDIN_CONTENT=${STDIN_CONTENT%x}
```

**Comment by fohte** [comment]
Hi @jvilk-stripe, thanks for reporting this and suggesting the solution!

This issue has fixed by #14, so I'll close this issue. If you still have any problems, please reopen it!
