### ISSUE TITLE
Any idea how to make this work w/ bundler?

### ISSUE THREAD

**Issue by amykyta** [fohte/rubocop-daemon#15]
Thanks for creating this, love the fast feedback. 

I have one issue though, my rubocop config is provided through a gem so to use it we need to run `bundle exec rubocop`. This doesn't work w/ the daemon as far as I can tell because it uses the `RuboCop::CLI` api. I briefly looked at Bundler's API but I am out of my depth on this. Any idea if it's possible to wrap that `RuboCop::CLI.new.run` in an equivalent of `bundle exec`?

**Comment by rylwin** [comment]
I came across this problem as well. Here's what I did to get it working:

1. Added rubocop-daemon to the project Gemfile. Mine looks like:

```
group :development do
  gem "rubocop-daemon", require: false
  gem "rubocop-rails", require: false
end
```

2a. Use the wrapper script mentioned in the readme, but modify line 87 so that:

```
if [ ! -f "$TOKEN_PATH" ]; then
  rubocop-daemon start
fi
```
becomes
```
if [ ! -f "$TOKEN_PATH" ]; then
  bundle exec rubocop-daemon start
fi
```

2b. Similar to the above, prefix line 112 with `bundle exec` as well

-----

Also, just want to say thanks for this project. I've been using it for 5 minutes and loving the speed with which rubocop is executing! :rocket:

**Comment by fohte** [comment]
Hi @amykyta, thanks for sharing this! And @rylwin, thanks for suggesting a solution!

For now, I think @rylwin's solution would be a great solution for this.

Today, I've added support for Bundler to `rubocop-daemon-wrapper` (6e5e68b), so you can make `rubocop-daemon-wrapper` work with Bundler now! :tada:
Please note that this feature is disabled by default, so you should set `$RUBOCOP_DAEMON_USE_BUNDLER` environment variable to enable it.

**Comment by jdelStrother** [comment]
This has been working great for me.  Any chance of a new gem release with it?

**Comment by fohte** [comment]
Hi @jdelStrother, thanks for reporting!

`rubocop-daemon-wrapper` is not a part of `rubocop-daemon` gem, so it is not versioned, but you can get it from GitHub.com directly (https://raw.githubusercontent.com/fohte/rubocop-daemon/master/bin/rubocop-daemon-wrapper).

By the way, it seems this issue has already resolved, so I'm going to close it.
If you still have any problems, please reopen it!
