### ISSUE TITLE
Automatically start the server if it's not running

### ISSUE THREAD

**Issue by ndbroadbent** [fohte/rubocop-daemon#2]
Hello,

I just searched for "RuboCop daemon" on Google, and was really happy to find this gem! Thanks for building this! I'm already seeing a huge speedup when running RuboCop.

I was wondering if it would be possible to automatically start the server if it's not already running? I think this would be better than showing an error: `rubocop-daemon: server is not running.`

**Comment by ndbroadbent** [comment]
I've also added a `exe/rubocop-wrapper` bash script that uses `netcat` to talk to the daemon. I'm blown away by how fast this is!!!

<img width="609" alt="screen shot 2018-12-15 at 3 21 49 pm" src="https://user-images.githubusercontent.com/139536/50040903-94923580-007e-11e9-9ba6-05961a0b59e0.png">

This is incredible. Thanks so much for working on this!

**Comment by fohte** [comment]
Big thanks to @ndbroadbent!
v0.3.0 ([GitHub](https://github.com/fohte/rubocop-daemon/releases/tag/v0.3.0), [RubeGems.org](https://rubygems.org/gems/rubocop-daemon/versions/0.3.0)) is released including your changes (#3)! :tada:

**Comment by ndbroadbent** [comment]
Awesome, thanks for merging the PR and releasing a new version! I hope that more Ruby developers will start using this gem, because it really makes development much nicer. 

I've posted about it in [this comment on a RuboCop issue](https://github.com/rubocop-hq/rubocop/issues/6492#issuecomment-447598459), so hopefully some RuboCop users and developers will see it and try this out.
